# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9917e6cac72d7de528aaade21c02f8a75255afbc0cf7c37619df41ba506aef4fdb0aba5d8af523c2dd44ee0269b4586cb2de7e56112fe39d62ef4f06a41b9bf5

test:
  secret_key_base: bfa2edeea60923c22e8005c37ecbd9bdad42a33dc12d8f75d91a45d6a559b51f7a6f093bdee258389e6b41c606ff30637ecce81b5e9af32850d07eeb2ee346d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
